# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.0.11
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: bun i
          build_command: bun run build-storybook
          path: storybook-static
          checkout: false
